name: moogallery
author: abidibo
category: Widgets
tags: [gallery, images, lightbox]
docs: http://www.abidibo.net/projects/js/moogallery
demo: http://www.abidibo.net/projects/js/moogallery/demo
current: 0.1
